### ISSUE TITLE
Enable multiple keystrokes without lifting comma

### ISSUE THREAD

**Issue by austinweisgrau** [susam/devil#2]
Love this package! Fare thee well, comma.

I quickly noticed that my normal pattern with ctrl is to hold it down while I hit the other keys for a command. For example, I hold down ctrl and then hit "x f" in succession. This translates to "C-x C-f"

However with devil mode, I need to hit the comma again each time I want to use it. If I hold down the comma and press "x f" this translates to "C-x f"

I'd love for it to be possible to keep that comma held down. Most emacs commands end up needing multiple keystrokes.

**Comment by susam** [comment]
@austinweisgrau Thank you for creating this issue. The decision to perform a "dumb" translation of comma (or the configured Devil key) to <kbd>ctrl</kbd> was deliberate. This has been elaborated in the section [Comparison with God Mode][CWGM] of the manual. Quoting the relevant portion below:

> Further note that in God mode the `C-` modifier has sticky behaviour, i.e., the modifier remains active automatically for the entire key sequence. Therefore in the above example, we type `,` only once while typing `, x f` to invoke `C-x C-f`. However, this sticky behaviour implies that we need some way to disambiguate between key sequences like `C-x C-f` (find-file) and `C-x o` (set-fill-column). God mode solves this by introducing `SPC` to deactivate the modifier, e.g., `x f` translates to `C-x C-f` but `x SPC o` translates to `C-x o`. Devil does not treat the modifier key as sticky which leads to simpler key sequences at the cost of a little additional typing, i.e., `, x , o` translates to `C-x C-o` and `, x o` translates to `C-x o`.

To summarize, simple and easy disambiguation between `C-x C-f` and `C-x f` with key sequences like `, x , f` and `, x f` (as opposed to `, x f` and `, x SPC f`) was the reason behind making `,` behave like `C-` in a non-sticky manner.

If you really want the `C-` behaviour to be sticky and if you are okay with the extra overhead of typing `SPC` when you want to make `C-` non-sticky, then god-mode might be a better tool for you. The same section mentioned earlier, i.e., the section [Comparison with God Mode][CWGM] discusses how to configure god-mode to achieve such a result.

[CWGM]: https://susam.github.io/devil/#comparison-with-god-mode

**Comment by susam** [comment]
The manual now has an FAQ section at <https://susam.github.io/devil/#frequently-asked-questions>. One of the entries in the FAQ discusses why sticky modifiers are not supported in Devil.
