### ISSUE TITLE
Cannot translate tab or backspace

### ISSUE THREAD

**Issue by morganwillcock** [susam/devil#5]
Hello!

I'm not sure whether this is expected to work, but it seems that some keys cannot be translated because the intercepted key name and the name used in key bindings is different.

For example, both `C-<tab>` and `C-<backspace>` are bound to a command:
```elisp
(where-is 'tab-next)
;; tab-next is on C-<tab>, C-x t o
(where-is 'backward-kill-word)
;; backward-kill-word is on C-<backspace>, M-DEL
```
...but the final result after translation appears to be looking up the key mapping with a different name:
`, <tab>`
Devil: C-TAB is undefined
`, <backspace>`
Devil: C-DEL is undefined

Is there any way to work around this?

**Comment by susam** [comment]
@morganwillcock This was a bug in the package. This bug has been fixed in commit 60f6968 and this fix is now available since version 0.4.0. Thank you for the detailed bug report. It helped make this package better.
